[package]
name = "world"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
rand_chacha = "0.9.0"
nbt = { git = "https://github.com/Cactus-minecraft-server/nbt.git" }
[lib]
name = "world"
path = "src/lib.rs"
[dev-dependencies]
image = "0.25.6"
